project:
  type: website
  output-dir: docs

website:
  title: "All the Right Questions"
  sidebar:
    contents: "auto"
format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    mainfont: "Trebuchet MS"

editor: visual


