project:
  type: website
  output-dir: docs

website:
  title: "All the Right Questions"
  sidebar:
    contents: "auto"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

