---
title: "All the Right Questions August 2026"
execute:
  echo: false
---

## Welcome!

Welcome to the 2nd edition of *All the Right Questions:* The new monthly newsletter for Church Army staff in which we think together about how we can get, share and use the data that we need to do the work that God has called us to. The format is still evolving, but I'm hoping to use this space to signpost resources, celebrate successes and remind you all that I exist and that I care about your professional relationship with data.

Thanks so much for joining me here. If you've got any questions, or if there's anything you'd like to see covered in a future edition of *ARQ*, please let me know! Drop me an email (I'm david.lovell), or just come and say hi to me at my desk.

This newsletter isn't an official Church Army publication and as such it doesn't represent the views of Church Army. Just me, Data Dave.

## This week:

-   [Really Good Survey Training in October](#sec-promotion): I'm very excited about it
-   [The lesson](#sec-lesson): Alex Dobson has psychic powers
-   [A Small Idea](#sec-big-idea): The grammar of data collection
-   [An incredible achivement](#sec-achievement): Printing custom QR-codes onto sticky-labels
-   [The puzzle](#sec-puzzle): Not really a puzzle at all - test yourself for psychic powers and get featured in the next episode of *All the Right Questions*!

## Really Good Survey Training in October! {#sec-promotion}

## A small idea: The grammar of data collection {#sec-big-idea}

## Something I'm proud of: Customised QR-codes on address labels! {#sec-achievement}

## The lesson: {#sec-lesson}

```{r psychic_business}
#| cache: true
library(purrr)
library(here)
library(ggplot2)
library(dplyr)

flip_cards <- readRDS(here("2026", "data", "flip-cards-function.RDS"))

psychic_scores <- seq(0, 1, 0.01)
success_scores <- map(psychic_scores, \(x) flip_cards(10, 4e6, x))


success_ratio <- function(x, threshold){
  sum(x >= threshold) / length(x)
}

score_prob <- map_dbl(success_scores, success_ratio, 85)

results <- 
  tibble(score_prob = score_prob,
         norm_score_prob = (score_prob - min(score_prob)) / max(score_prob),
         norm_prob_diff = norm_score_prob - lag(norm_score_prob, default = 0),
         psych_score  = psychic_scores)

ggplot(results) + 
  
  geom_area(aes(x = psych_score, y = norm_prob_diff),
            fill = "blue", alpha = 0.5) + 
  
  theme_minimal()

results

```

## The Puzzle {#sec-puzzle}

Not actually a puzzle at all. It's your turn to test yourself for psychic powers, using this [clever widget](https://church-army.shinyapps.io/psychic-tester/) I've built. Tune in next month to find out whether or not you are psychic!
